services:
  shop-db:
    image: postgres:16.1-alpine
    container_name: shop-postgres-db
    restart: on-failure
    env_file:
      - .env
    ports:
      - "${POSTGRESQL_EXT_PORT}:${POSTGRESQL_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - shop-postgres-db-data:/var/lib/postgresql/data
volumes:
  shop-postgres-db-data: